CREATE USER 'art_shop'@'localhost' IDENTIFIED BY 'shop_pass';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD, INDEX
on *.* TO 'art_shop'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS art_shop_database;
